### ISSUE TITLE
Best Practices to Handle Grant Release from an ISR

### ISSUE THREAD

**Issue by justacec** [jamesmunns/office-hours#13]
# Problem Statement
I have been working to use the BBQueue crate with the RTFM framework.  I think that I have it mostly all inlace with the exception of 1 issue, how to tell the `release` method of a `GrantR` object how much memory to free up when it is called as an ISR and outside of the scope of the function that generated the `GrantW`.

The code for this question can be found at: [https://gist.github.com/justacec/3e54d4d7d7f3a3da860a5b40bc02a77e](https://gist.github.com/justacec/3e54d4d7d7f3a3da860a5b40bc02a77e)

# Example Code Description
The example code attempts to use the RTFM framework to generate an echo server on the SPI line of a STM32F407.  The general approach for the initialization is:

 0. Place 8 state variable in the `resources` structure to maintain all things (Lines 54 - 61)
 1. Establish the SPI device as a slave (Lines 113 - 158)
 2. Split out the each of the Rx and Tx BBQueue buffers to their prod, cons pairs (Lines 161 and 162)
 3. Generate a `GrantW` from the Rx producer 
 4. Setup two DMA streams (one for SPI Rx and one for SPI Tx) (Lines 169 - 221)
 5. Enable the DMA Rx stream
 6. Store all the states of the BBQueue objects in the `LateResources` instance. (Lines 230 - 245)
 
The `resources` elements are the producers and consumers for each of the rx and tx channels in addition to holding the active grants for each of these.  The grants were not stored in there previously but we found after some discussion that they needed to be there in order be able to communicate between different functions in the RTFM framework.  They are implemented as `Option` as they are `None` to begin with (with the exception of the initial Rx producer `GrantW`. 

The communications on the SPI are handled in the following way:

 1. The SPI is set to an SPI_State::WaitForCommand
 2. Data is received and piped into the BBQ Rx GrantW by the DMA
 3. The `spi_complete` function is called when the SS line goes high via the `EXTI15_10` ISR (Lines 360 - 398)
  4. The `process_command` function extracts the data from the Rx buffer, processes the desired command (in this case just an echo)
  5. The `process_command` function requests a Tx GrantW to place the return data and copies the return data into the buffer
  6. The `process_command` function then creates a Tx GrantR and passes the buffer to the DMA
  7. The `process_command` function then enables the DMA line
  8. The SPI master then requests N bytes of data (because it knows how much to ask for based on the protocol)
  9. The `spi_complete` function is called when the SS line goes high via the `EXTI15_10` ISR 
  10. The `spi_complete` function releases the Tx GrantRm, resets the state and clears things out for the next comms request from the master.

Also, I did not put it in there but at the beginning of the `process_command` function, one of the GPIO pins is set to high indicating to the SPI master that the MCU is busy processing a request.  At the end of the `process_command` function, that GPIO is set low.  The SPI master waits for the line to go low to request the response.

# Problem Discussion
The issue if specifically present in line 391 of `main.rs`.  As the GrantR is cleared in a separate function call, it does not know how much to free.  So I see 2 possible COA:

  1. Create a new entry in the `resources` struct to hold the amount of data in the Tx buffer
  2. Just always release 32 bytes 

I was a bit hesitant to add another entry into the `resources` table as I have already used 8 places for the buffering.  (Maybe the current 8 are not the most efficient approach, suggestions welcome). I thought about getting it from the DMA registers but the `NCNT` of course goes backwards and will be in a state of 0 at then end of the transmission.

# Specific Questions

  1. How do I inform the ISR on the amount of data that was sent so I can release the correct amount?
  2. Is there a more efficient way to include BBQueue in RTFM?
  3. Based on what is seen here and my use case, should I be using BBQueue or should I switch back to simple linear buffers?

**Comment by thalesfragoso** [comment]
>  I thought about getting it from the DMA registers but the NCNT of course goes backwards and will be in a state of 0 at then end of the transmission. 

If you know what was in the `NDTR` before,  can't you calculate how much it copied ?

**Comment by jamesmunns** [comment]
Discussed on stream!
